version: "3.3"
services:
  frontrp:
    build: ./frontrp
    image: frontrp:latest
    container_name: frontrp
    hostname: frontrp
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
      - NGINX_PORT_TLS=443
      - NGINX_HOST=0.0.0.0
      - WILMA=http://sec_wilma_pub:8080
      - KEYROCK=http://<IP>:3000
      - DASHBOARD=http://<IP>:80
      - DASHBOARD_BACKEND=http://<IP>:80
    depends_on: 
      - sec_wilma
    networks:
      - proxy
  sec_wilma_pub:
    image: marcdespland/fiware-pep-proxy
    container_name: sec_wilma_pub
    hostname: sec_wilma_pub
    environment:
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_PUBLIC_PATHS=/public
      - PEP_PROXY_AZF_PORT=3080
      - PEP_PROXY_AZF_HOST=<IP>
      - PEP_PROXY_AZF_PROTOCOL=http
      - PEP_PROXY_PDP=authzforce
      - PEP_PROXY_APP_SSL_ENABLED=false
      - PEP_PROXY_APP_PORT=8080
      - PEP_PROXY_APP_HOST=172.22.2.4
      - PEP_PROXY_APP_ID=24c00968-b065-4f5e-a1be-b72602257be3
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3000
      - PEP_PROXY_IDM_HOST=<IP>
      - PEP_PROXY_PORT=8080
      - PEP_PASSWORD_FILE=/run/secrets/sec_wilma_pub.password
      - PEP_PROXY_USERNAME_FILE=/run/secrets/sec_wilma_pub.proxy.username
    depends_on: 
      - dalproxy
    networks:
      - dal_proxy
    secrets:
      - sec_wilma_pub.token.secret
      - sec_wilma_pub.password
      - sec_wilma_pub.proxy.username
  dalproxy:
    image: pixel/dalproxy:1.1.0
    container_name: dal_proxy
    hostname: dal_proxy
    environment:
      - API_LISTEN_PORT=8080
      - API_LISTEN_IP=172.22.1.4
      - PROXY_LISTEN_PORT=8080
      - PROXY_LISTEN_IP=172.22.2.4
      - PROXY_API_TOKEN_FILE=/run/secrets/dal.proxy.api.token
      - ORCHESTRATOR_API_URL=http://172.22.1.3:8080
      - ORCHESTRATOR_TOKEN_FILE=/run/secrets/dal.orchestrator.api.token
    secrets:
      - dal.proxy.api.token
      - dal.orchestrator.api.token
    network:
      dal:
        ipv4_address: 172.22.1.4
      dal_agents:
      dal_proxy:
        ipv4_address: 172.22.2.4
  dalorchestrator:
    image: pixel/dalorchestrator:1.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    container_name: dal_orchestrator
    hostname: dal_orchestrator
    environment:
      - NGSIAGENT_NETWORK=dal_agents
      - NGSIAGENT_KEY=pixel
      - PROXY_API_URL=http://172.22.1.4:8080
      - PROXY_API_TOKEN_FILE=/run/secrets/dal.proxy.api.token
      - ORCHESTRATOR_LISTEN_PORT=8080
      - ORCHESTRATOR_LISTEN_IP="172.22.1.3"
      - ORCHESTRATOR_TOKEN_FILE=/run/secrets/dal.orchestrator.api.token
    secrets:
      - dal.proxy.api.token
      - dal.orchestrator.api.token
    network:
      dal:
        ipv4_address: 172.22.1.3
networks:
  proxy:
  dal:
    ipam:
      config:
        - subnet: 172.22.1.0/24
  dal_agents:
  dal_proxy:
    ipam:
      config:
        - subnet: 172.22.2.0/24
secrets:
  dal.proxy.api.token:
    file: ./secrets/dal.proxy.api.token
  dal.orchestrator.api.token:
    file: ./secrets/dal.orchestrator.api.token
  sec_wilma_pub.token.secret:
    file: ./secrets/sec_wilma_pub.token.secret
  sec_wilma_pub.password:
    file: ./secrets/sec_wilma_pub.password
  sec_wilma_pub.proxy.username:
    file: ./secrets/sec_wilma_pub.proxy.username