version: "3.3"
services:
  frontrp:
    restart: always
    build: ./frontrp-insiel
    image: frontrp:latest
    container_name: frontrp
    hostname: frontrp
    ports:
      - 80:80
      - 443:443
      - 8090:8090
      - 8091:8091
    extra_hosts:
      - ih.pixel.internal:10.12.182.193
    environment:
      - NGINX_PORT=80
      - NGINX_TLS_PORT=443
      - NGINX_HOST=0.0.0.0
      - WILMA_HOST=172.40.1.4
      - KEYROCK_HOST=${CORE_HOST_IP}
      - DASHBOARD_WEB_HOST=${CORE_HOST_IP}
      - DASHBOARD_BACKEND_HOST=${CORE_HOST_IP}
      - OPERATIONTOOLS_API_HOST=${CORE_HOST_IP}
      - KIBANA_HOST=${CORE_HOST_IP}
      - NAGIOS_HOST=${CORE_HOST_IP}
      - PIXEL_DOMAIN=${PIXEL_DOMAIN}
      - PIXEL_INTERNAL_DOMAIN=${PIXEL_INTERNAL_DOMAIN}
      - PIXEL_ADMIN_PASSWORD_FILE=/run/secrets/frontrp.admin.password
    depends_on: 
      - sec-wilma-pub
    secrets:
      - frontrp.admin.password
    networks:
      proxy:
        ipv4_address: 172.40.1.5
  sec-wilma-pub:
    restart: always
    image: marcdespland/fiware-pep-proxy
    container_name: sec-wilma-pub
    hostname: sec-wilma-pub
    ports:
      - 8081:8080
    environment:
      - PEP_PROXY_AUTH_ENABLED=true
      - PEP_PROXY_PUBLIC_PATHS=/public
      - PEP_PROXY_AZF_PORT=3080
      - PEP_PROXY_AZF_HOST=${CORE_HOST_IP}
      - PEP_PROXY_AZF_PROTOCOL=http
      - PEP_PROXY_PDP=authzforce
      - PEP_PROXY_APP_SSL_ENABLED=false
      - PEP_PROXY_APP_PORT=8080
      - PEP_PROXY_APP_HOST=172.43.1.2
      - PEP_PROXY_APP_ID=${PEP_PROXY_APP}
      - PEP_PROXY_IDM_SSL_ENABLED=false
      - PEP_PROXY_IDM_PORT=3000
      - PEP_PROXY_IDM_HOST=${CORE_HOST_IP}
      - PEP_PROXY_PORT=8080
      - PEP_PASSWORD_FILE=/run/secrets/sec_wilma_pub.password
      - PEP_PROXY_USERNAME_FILE=/run/secrets/sec_wilma_pub.proxy.username
    depends_on: 
      - dal-proxy
    networks:
      proxy:
        ipv4_address: 172.40.1.4
      dal_proxy:
        ipv4_address: 172.43.1.4
    secrets:
      - sec_wilma_pub.token.secret
      - sec_wilma_pub.password
      - sec_wilma_pub.proxy.username
  dal-proxy:
    restart: always
    image: pixelh2020/dal-proxy:1.1.0
    container_name: dal-proxy
    hostname: dal-proxy
    environment:
      - API_LISTEN_PORT=8080
      - API_LISTEN_IP=172.41.1.2
      - PROXY_LISTEN_PORT=8080
      - PROXY_LISTEN_IP=172.43.1.2
      - PROXY_API_TOKEN_FILE=/run/secrets/dal.proxy.api.token
      - ORCHESTRATOR_API_URL=http://172.41.1.3:8080
      - ORCHESTRATOR_TOKEN_FILE=/run/secrets/dal.orchestrator.api.token
    secrets:
      - dal.proxy.api.token
      - dal.orchestrator.api.token
    networks:
      dal:
        ipv4_address: 172.41.1.2
      dal_agents:
        ipv4_address: 172.42.1.2
      dal_proxy:
        ipv4_address: 172.43.1.2
  dal-orchestrator:
    restart: always
    image: pixelh2020/dal-orchestrator:1.3.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/pixel/Data_Models/specs:/opt/schemas
    ports:
      - 8080:8080
    container_name: dal-orchestrator
    hostname: dal-orchestrator
    environment:
      - SCHEMA_REPOSITORY_URL=http://schemas${PIXEL_INTERNAL_DOMAIN}
      - SCHEMA_REPOSITORY=/opt/schemas
      - NGSIAGENT_NETWORK=public_dal_agents
      - NGSIAGENT_KEY=pixel
      - PROXY_API_URL=http://172.41.1.2:8080
      - PROXY_API_TOKEN_FILE=/run/secrets/dal.proxy.api.token
      - ORCHESTRATOR_LISTEN_PORT=8080
      - ORCHESTRATOR_LISTEN_IP=172.41.1.3
      - ORCHESTRATOR_TOKEN_FILE=/run/secrets/dal.orchestrator.api.token
      - ORION_API=http://${CORE_HOST_IP}:1026
    secrets:
      - dal.proxy.api.token
      - dal.orchestrator.api.token
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      dal:
        ipv4_address: 172.41.1.3
  nagios:
    restart: always
    build: ./nrpe
    image: nrpe-public:latest
    container_name: nrpe
    hostname: nrpe
    environment:
      - NAGIOS_HOST=${CORE_HOST_IP}
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    ports:
      - 5666:5666
    networks:
      proxy:
        ipv4_address: 172.40.1.200
      dal:
        ipv4_address: 172.41.1.200
      dal_agents:
        ipv4_address: 172.42.1.200
      dal_proxy:
        ipv4_address: 172.43.1.200
networks:
  proxy:
    ipam:
      config:
        - subnet: 172.40.1.0/24
  dal:
    ipam:
      config:
        - subnet: 172.41.1.0/24
  dal_agents:
    ipam:
      config:
        - subnet: 172.42.1.0/24
  dal_proxy:
    ipam:
      config:
        - subnet: 172.43.1.0/24
secrets:
  dal.proxy.api.token:
    file: ./secrets/dal.proxy.api.token
  dal.orchestrator.api.token:
    file: ./secrets/dal.orchestrator.api.token
  sec_wilma_pub.token.secret:
    file: ./secrets/sec_wilma_pub.token.secret
  sec_wilma_pub.password:
    file: ./secrets/sec_wilma_pub.password
  sec_wilma_pub.proxy.username:
    file: ./secrets/sec_wilma_pub.proxy.username
  frontrp.admin.password:
    file: ./secrets/frontrp.admin.password
