FROM pixelh2020/ot:0.1
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY context.xml /usr/local/tomcat/conf/Catalina/localhost/manager.xml
COPY context.xml /usr/local/tomcat/conf/Catalina/localhost/host-manager.xml
COPY default.configuration.xml /usr/local/tomcat/default.configuration.xml