version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper_data:/var/opt/zookeeper
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.5
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.24.1.6
      KAFKA_CREATE_TOPICS: "data:1:1,status:1:1,notifications:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.6
  orion-collector:
    image: docker.pixel-ports.eu/information-hub/orion-data-collector
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.6
      - csco.archiving.config:172.24.1.5
      - csco.archiving.sts:172.24.1.7
      - csco.archiving.lts:172.24.1.7
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.9
  controller:
    image: docker.pixel-ports.eu/information-hub/information-hub-controller
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.6
      - csco.archiving.config:172.24.1.5
      - csco.archiving.sts:172.24.1.7
      - csco.archiving.lts:172.24.1.7
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.10
  extractor:
    image: docker.pixel-ports.eu/information-hub/srv-data-extractor
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.6
      - csco.archiving.config:172.24.1.5
      - csco.archiving.sts:172.24.1.7
      - csco.archiving.lts:172.24.1.7
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.11
      ih_public:
  monitor:
    image: docker.pixel-ports.eu/information-hub/srv-data-monitor
    depends_on:
      - zookeeper
      - kafka
      - controller
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.6
      - csco.archiving.config:172.24.1.5
      - csco.archiving.sts:172.24.1.7
      - csco.archiving.lts:172.24.1.7
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.12

  writer:
    image: docker.pixel-ports.eu/information-hub/srv-data-writer
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.6
      - csco.archiving.config:172.24.1.5
      - csco.archiving.sts:172.24.1.7
      - csco.archiving.lts:172.24.1.7
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.13
  elasticsearch-proxy:
    image: docker.pixel-ports.eu/information-hub/elasticsearch-proxy
    environment:
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.14
      ih_public:

volumes:
  zookeeper_data:
    driver: local
