version: "3.3"
services:
  internal_proxy:
    build: ./internal_proxy
    image: internal-proxy:latest
    container_name: internal-proxy
    hostname: internal-proxy
    environment:
      - NGINX_PORT=80
      - NGINX_TLS_PORT=443
      - NGINX_HOST=0.0.0.0
      - PIXEL_DOMAIN=pixel.internal
      - IH_DATA_EXTRACTOR_HOST=sec-wilma-pub
      - SEC_KEYROCK_HOST=sec-keyrock
      - IH_ELASTICSEARCH_PROXY_HOST=<IP HOST CORE>
      - SEC_AUTHZFORCE_HOST=sec-authzforce
      - DAL_ORCHESTRATOR_HOST=<IP HOST PUBLIC>
    depends_on: 
      - ih-data-extractor
      - ih-elacticsearch-proxy
      - sec-keyrock
      - sec-authzforce
    networks:
      - ih_public
      - security
  sec_keyrock:
    build: ./keyrock
    image: sec-keyrock:7.8.0
    container_name: sec-keyrock
    hostname: sec-keyrock
    networks:
      security:
      security_db:
        ipv4_address: 172.21.1.5
    depends_on:
      - sec-mysql-db
    ports:
      - "3000:3000"
    environment:
      - IDM_CORS_ENABLED=true 
      - IDM_DB_HOST=sec-mysql-db
      - IDM_HOST=http://<IP HOST CORE>:3000
      - IDM_PORT=3000
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@example.com
      - IDM_EMAIL_ADDRESS=noreply@example.com
      - IDM_TITLE=My Identity Manager
      - IDM_THEME=pixel
      - IDM_PDP_LEVEL=advanced
      - IDM_AUTHZFORCE_ENABLED=true
      - IDM_AUTHZFORCE_HOST=authzforce
      - IDM_SESSION_SECRET_FILE=/run/secrets/idm.session.secret
      - IDM_ENCRYPTION_KEY_FILE=/run/secrets/idm.encryption.key 
      - IDM_DB_PASS_FILE=/run/secrets/idm.db.pass
      - IDM_ADMIN_PASS_FILE=/run/secrets/idm.admin.pass
    secrets:
      - idm.session.secret
      - idm.encryption.key
      - idm.db.pass
      - idm.admin.pass
  sec-mysql-db:
    restart: always
    image: mysql:5.7
    hostname: sec-mysql-db
    container_name: sec-mysql-db
    networks:
      security_db:
        default:
          ipv4_address: 172.21.1.6
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/idm.db.pass
      - MYSQL_ROOT_HOST=172.21.1.5
    volumes:
      - mysql-db:/var/lib/mysql
    secrets:
      - idm.db.pass
  sec-authzforce:
    restart: always
    image: fiware/authzforce-ce-server:release-8.1.0
    hostname: sec-authzforce
    container_name: sec-authzforce
    ports:
      - 3080:8080
    networks:
      security:
  dal-orion-db:
    image: mongo
    command: --auth
    hostname: dal-orion-db
    container_name: dal-orion-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo 
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/orion.db.root.password 
      - MONGO_INITDB_DATABASE=admin
      - ORIONDB_PASSWORD_FILE=/run/secrets/orion.db.password
    volumes:
      - orion-db:/data/db
      - ./oriondb:/docker-entrypoint-initdb.d
    networks:
      - dal-db
    secrets:
      - orion.db.root.password
      - orion.db.password
  dal-orion:
    build: ./orion
    image: pixel-orion
    environment:
      - DB_HOST=dal-orion-db 
      - DB=orion 
      - DB_USER=orion 
      - DB_PASSWORD_FILE=/run/secrets/orion.db.password
    depends_on:
      - dal-orion-db
    ports:
      - "1026:1026"
    networks:
      - dal
      - dal-db
    secrets:
      - orion.db.password
volumes:
  mysql-db:
  orion-db:
networks:
  ih_public:
  ih:
  security:
  security_db:
    ipam:
      config:
        - subnet: 172.21.1.0/24
  dal_db:
  dal:
secrets:
  idm.session.secret:
    file: ./secrets/idm.session.secret
  idm.encryption.key:
    file: ./secrets/idm.encryption.key
  idm.db.pass:
    file: ./secrets/idm.db.pass
  idm.admin.pass:
    file: ./secrets/idm.admin.pass
  orion.db.root.password:
    file: ./secrets/orion.db.root.password
  orion.db.password:
    file: ./secrets/orion.db.password



