version: '3.3'
services:
  nagios:
    build:
      context: ./nagios
      args:
        - PIXEL_DOMAIN=${PIXEL_DOMAIN}
        - PUBLIC_HOST_IP=${PUBLIC_HOST_IP}
        - CORE_HOST_IP=${CORE_HOST_IP}
    image: nagios-core:latest
    restart: always
    container_name: nagios
    hostname: nagios
    environment:
      - NAGIOSADMIN_PASSWORD_FILE=/run/secrets/nagios.ngiosadmin.password
      - ORIONDB_PASSWORD_FILE=/run/secrets/orion.db.password
      - OTDB_PASSWORD_FILE=/run/secrets/ot.db.password
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    ports:
      - 8088:80
    secrets:
      - nagios.ngiosadmin.password
      - orion.db.password
    networks:
      pixel:
        ipv4_address: 172.29.1.200
      ih:
        ipv4_address: 172.24.1.200
      ih_public:
        ipv4_address: 172.25.1.200
      security:
        ipv4_address: 172.26.1.200
      security_db:
        ipv4_address: 172.23.1.200
      dal_db:
        ipv4_address: 172.27.1.200
      dal:
        ipv4_address: 172.28.1.200
  dal-provisioning:
    image: pixelh2020/dal-provisioning:1.0.1
    hostname: dal-provisioning
    container_name: dal-provisioning
    environment:
      - KEYROCK_ADMIN_PASSWORD_FILE=/run/secrets/idm.admin.pass
      - KEYROCK_ADMIN_LOGIN=admin@pixel-ports.eu
      - KEYROCK_API=http://172.26.1.6:3000
      - ORION_API=http://172.28.1.10:1026
      - DAL_INQUISITOR_API=http://172.28.1.201:8080
    networks:
      dal:
        ipv4_address: 172.28.1.201
      security:
        ipv4_address: 172.26.1.201
    secrets:
      - idm.admin.pass
    logging:
      options:
        max-size: "15m"
        max-file: "2"
