version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    volumes:
      - zookeeper_data:/var/opt/zookeeper
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.13
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: LISTENER_IH://172.24.1.14:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_IH://172.24.1.14:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_IH:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_IH
      KAFKA_CREATE_TOPICS: "data:1:1,status:1:1,notifications:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 172.24.1.13:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.14
  orion-collector:
    image: docker.pixel-ports.eu/information-hub/orion-data-collector
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
      - dal-orion
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.14
      - csco.archiving.config:172.24.1.13
      - csco.archiving.sts:172.24.1.11
      - csco.archiving.lts:172.24.1.11
      - dal-orion:172.28.1.10
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.15
      dal:
        ipv4_address: 172.28.1.15
  controller:
    image: docker.pixel-ports.eu/information-hub/information-hub-controller
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.14
      - csco.archiving.config:172.24.1.13
      - csco.archiving.sts:172.24.1.11
      - csco.archiving.lts:172.24.1.11
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.16
  extractor:
    image: docker.pixel-ports.eu/information-hub/srv-data-extractor
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.14
      - csco.archiving.config:172.24.1.13
      - csco.archiving.sts:172.24.1.11
      - csco.archiving.lts:172.24.1.11
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.17
      ih_public:
        ipv4_address: 172.25.1.17
  monitor:
    image: docker.pixel-ports.eu/information-hub/srv-data-monitor
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - controller
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.14
      - csco.archiving.config:172.24.1.13
      - csco.archiving.sts:172.24.1.11
      - csco.archiving.lts:172.24.1.11
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.18

  writer:
    image: docker.pixel-ports.eu/information-hub/srv-data-writer
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - csco.archiving.broker:172.24.1.14
      - csco.archiving.config:172.24.1.13
      - csco.archiving.sts:172.24.1.11
      - csco.archiving.lts:172.24.1.11
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.19
  elasticsearch-proxy:
    image: docker.pixel-ports.eu/information-hub/elasticsearch-proxy
    restart: always
    environment:
      - ELASTICSEARCH_ADDRESS=172.24.1.11:9200
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.20
      ih_public:
        ipv4_address: 172.25.1.20

volumes:
  zookeeper_data:
    driver: local
