version: "3.3"
services:
  internal_proxy:
    restart: always
    build: ./internal_proxy
    image: internal-proxy:latest
    container_name: internal-proxy
    hostname: internal-proxy
    ports:
      - 127.0.0.1:443:443
    environment:
      - NGINX_PORT=80
      - NGINX_TLS_PORT=443
      - NGINX_HOST=0.0.0.0
      - PIXEL_DOMAIN=${PIXEL_INTERNAL_DOMAIN}
      - IH_DATA_EXTRACTOR_HOST=172.25.1.17
      - SEC_KEYROCK_HOST=172.26.1.6
      - IH_ELASTICSEARCH_PROXY_HOST=172.25.1.20
      - SEC_AUTHZFORCE_HOST=172.26.1.8
      - DAL_ORCHESTRATOR_HOST=${PUBLIC_HOST_IP}
    depends_on: 
      - extractor
      - elasticsearch-proxy
      - sec-keyrock
      - sec-authzforce
    networks:
      pixel:
        ipv4_address: 172.29.1.5
      ih_public:
        ipv4_address: 172.25.1.5
      security:
        ipv4_address: 172.26.1.5
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  sec-keyrock:
    build: ./keyrock
    restart: always
    image: sec-keyrock:7.8.0
    container_name: sec-keyrock
    hostname: sec-keyrock
    networks:
      security:
        ipv4_address: 172.26.1.6
      security_db:
        ipv4_address: 172.23.1.6
    depends_on:
      - sec-mysql-db
    ports:
      - "3000:3000"
    environment:
      - IDM_CORS_ENABLED=true 
      - IDM_DB_HOST=sec-mysql-db
      - IDM_HOST=http://${CORE_HOST_IP}:3000
      - IDM_PORT=3000
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@pixel-ports.eu
      - IDM_EMAIL_ADDRESS=noreply@pixel-ports.eu
      - IDM_TITLE=Pixel Identity Manager
      - IDM_THEME=pixel
      - IDM_PDP_LEVEL=advanced
      - IDM_AUTHZFORCE_ENABLED=true
      - IDM_AUTHZFORCE_HOST=authzforce
      - IDM_SESSION_SECRET_FILE=/run/secrets/idm.session.secret
      - IDM_ENCRYPTION_KEY_FILE=/run/secrets/idm.encryption.key 
      - IDM_DB_PASS_FILE=/run/secrets/idm.db.pass
      - IDM_ADMIN_PASS_FILE=/run/secrets/idm.admin.pass
    secrets:
      - idm.session.secret
      - idm.encryption.key
      - idm.db.pass
      - idm.admin.pass
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  sec-mysql-db:
    restart: always
    image: mysql:5.7
    hostname: sec-mysql-db
    container_name: sec-mysql-db
    networks:
      security_db:
          ipv4_address: 172.23.1.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/idm.db.pass
      - MYSQL_ROOT_HOST=172.23.1.*
    volumes:
      - mysql-db:/var/lib/mysql
    secrets:
      - idm.db.pass
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  sec-authzforce:
    restart: always
    image: fiware/authzforce-ce-server:release-8.1.0
    hostname: sec-authzforce
    container_name: sec-authzforce
    ports:
      - 3080:8080
    networks:
      security:
        ipv4_address: 172.26.1.8
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  dal-orion-db:
    image: mongo
    restart: always
    command: --auth
    hostname: dal-orion-db
    container_name: dal-orion-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo 
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/orion.db.root.password 
      - MONGO_INITDB_DATABASE=admin
      - ORIONDB_PASSWORD_FILE=/run/secrets/orion.db.password
    volumes:
      - orion-db:/data/db
      - ./oriondb:/docker-entrypoint-initdb.d
    networks:
      dal_db:
        ipv4_address: 172.27.1.9
    secrets:
      - orion.db.root.password
      - orion.db.password
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  dal-orion:
    build: ./orion
    restart: always
    image: pixel-orion
    environment:
      - DB_HOST=dal-orion-db 
      - DB=orion 
      - DB_USER=orion 
      - DB_PASSWORD_FILE=/run/secrets/orion.db.password
    depends_on:
      - dal-orion-db
    ports:
      - "1026:1026"
    networks:
      dal:
        ipv4_address: 172.28.1.10
      dal_db:
        ipv4_address: 172.27.1.10
    secrets:
      - orion.db.password
    logging:
      options:
        max-size: "15m"
        max-file: "2"
  dal-inquisitor:
    image: pixelh2020/dal-inquisitor:1.0.0
    restart: always
    hostname: dal-inquisitor
    container_name: dal-inquisitor
    environment:
      - ORION_URL=http://172.28.1.10:1026
    depends_on:
      - dal-orion
    networks:
      dal:
        ipv4_address: 172.28.1.21
volumes:
  mysql-db:
  orion-db:
networks:
  ih_public:
    ipam:
      config:
        - subnet: 172.25.1.0/24
  ih:
    ipam:
      config:
        - subnet: 172.24.1.0/24
  security:
    ipam:
      config:
        - subnet: 172.26.1.0/24
  security_db:
    ipam:
      config:
        - subnet: 172.23.1.0/24
  dal_db:
    ipam:
      config:
        - subnet: 172.27.1.0/24
  dal:
    ipam:
      config:
        - subnet: 172.28.1.0/24
  pixel:
    ipam:
      config:
        - subnet: 172.29.1.0/24
  ot:
    ipam:
      config:
        - subnet: 172.30.1.0/24
secrets:
  idm.session.secret:
    file: ./secrets/idm.session.secret
  idm.encryption.key:
    file: ./secrets/idm.encryption.key
  idm.db.pass:
    file: ./secrets/idm.db.pass
  idm.admin.pass:
    file: ./secrets/idm.admin.pass
  orion.db.root.password:
    file: ./secrets/orion.db.root.password
  orion.db.password:
    file: ./secrets/orion.db.password
  nagios.ngiosadmin.password:
    file: ./secrets/nagios.ngiosadmin.password


