version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/opt/zookeeper
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.13
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.24.1.14
      KAFKA_CREATE_TOPICS: "data:1:1,status:1:1,notifications:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 172.24.1.13:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.14
  orion-collector:
    image: pixelh2020/information-hub-orion-data-collector:1.5.2
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
      - dal-orion
    volumes:
      - ./ih-config:/etc/inf-hub
    extra_hosts:
      - dal-orion:172.28.1.10
      - schemas.pixel.internal:172.24.1.30
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.15
      dal:
        ipv4_address: 172.28.1.15
  controller:
    image: pixelh2020/information-hub-controller:1.2.0
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.16
  extractor:
    image: pixelh2020/information-hub-extractor:1.2.0
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.17
      ih_public:
        ipv4_address: 172.25.1.17
  monitor:
    image: pixelh2020/information-hub-monitor:1.2.0
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - controller
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.18

  writer:
    image: pixelh2020/information-hub-writer:1.2.3
    restart: always
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    volumes:
      - ./ih-config:/etc/inf-hub
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.19
  elasticsearch-proxy:
    image: pixelh2020/information-hub-elasticsearch-proxy:1.2.1
    restart: always
    environment:
      - ELASTICSEARCH_ADDRESS=172.24.1.11:9200
    depends_on:
      - elasticsearch
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.20
      ih_public:
        ipv4_address: 172.25.1.20
  orchestrator:
    image: pixelh2020/information-hub-data-processor-orchestrator:1.2.0
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./ih-config:/etc/inf-hub
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.29
      ih_public:
        ipv4_address: 172.25.1.29
  ih-health-probe:
    image: pixelh2020/ih-health-probe:v0.2.1
    depends_on:
      - zookeeper
      - kafka
      - orchestrator
      - writer
      - monitor
      - extractor
      - controller
      - orion-collector
    volumes:
      - /opt/pixel/kpi/ih:/output
    logging:
      options:
        max-size: "15m"
        max-file: "2"
    networks:
      ih:
        ipv4_address: 172.24.1.32
      ih_public:
        ipv4_address: 172.25.1.32
volumes:
  zookeeper_data:
    driver: local
