version: "3.3"
networks:
  ih_public:
    ipam:
      config:
        - subnet: 172.25.1.0/24
  ih:
    ipam:
      config:
        - subnet: 172.24.1.0/24
  security:
    ipam:
      config:
        - subnet: 172.26.1.0/24
  security_db:
    ipam:
      config:
        - subnet: 172.23.1.0/24
  dal_db:
    ipam:
      config:
        - subnet: 172.27.1.0/24
  dal:
    ipam:
      config:
        - subnet: 172.28.1.0/24
  pixel:
    ipam:
      config:
        - subnet: 172.29.1.0/24
  ot:
    ipam:
      config:
        - subnet: 172.30.1.0/24
  dash-api-db:
    ipam:
      config:
        - subnet: 172.31.1.0/24


