version: "3.3"
services:
  otdb:
    image: mongo
    container_name: otdb
    command: --auth
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo 
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/ot.db.root.password 
      - MONGO_INITDB_DATABASE=admin
      - OTDB_DATABASE=otpixel
      - OTDB_PASSWORD_FILE=/run/secrets/ot.db.password
    networks:
      ot:
        ipv4_address: 172.30.1.22
    volumes:
      - ot-db:/data/db
      - ./otdb:/docker-entrypoint-initdb.d
    secrets:
      - ot.db.root.password
      - ot.db.password
secrets:
  ot.db.root.password:
    file: ./secrets/ot.db.root.password
  ot.db.password:
    file: ./secrets/ot.db.password
volumes:
  ot-db: